language: java
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
install:
  - set -ev
  - java -version
  - ./gradlew --version
  - npm install -g bower
  - npm install -g grunt-cli
  - ./gradlew assemble
script:
  - ./gradlew check
