os:
  - linux
services:
  - dockeri
language: java
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install:
  - sudo /etc/init.d/postgresql stop
install:
  - set -ev
  - java -version
  - ./gradlew --version
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - ./gradlew assemble
script:
  - ./gradlew check
  - docker-compose up -d
  - sleep 20s
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./gradlew bootRun &
  - bootPid=$!
  - sleep 120s
  - grunt itest
